/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Bottle() {
  const group = useRef(null)
  // useFrame(() => (group.current.rotation.y += 0.01));
  const { nodes, materials } = useGLTF('../logos/bottle1-transformed.glb')
  return (
    <group ref={group} dispose={null} scale={.09} position={[0, -7.8, 0]}>
      <mesh castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials['Material.001']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_1.geometry} material={materials['Material.002']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_2.geometry} material={materials['Material.003']} />
      <mesh castShadow receiveShadow geometry={nodes.Cube002_3.geometry} material={materials['Material.004']} />
    </group>
  )
}

useGLTF.preload('../logos/bottle1-transformed.glb')
