/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BullsEye({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('../logos/bullseye1-transformed.glb')
  return (
    <group rotation={[-Math.PI / -2, 0, 0]} scale={.5} position={[-5, -12.5, .1]} ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('../logos/bullseye1-transformed.glb')
